// AUTO-GENERATED. DO NOT EDIT.
// Targets Aggregate generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

public let targets: [Target] = [
	.app
]

public let appProjectTargets: [Target] = [
	.app
]

public extension Destinations {
	static var appDestinations: Destinations { environment.destinations }
}

public extension DeploymentTargets {
	static var appDeploymentTargets: DeploymentTargets { environment.deploymentTargets }
}

public protocol TargetDependencies {
	static var appDependencies: [TargetDependency] { get }
}

public extension TargetDependencies {
	static var appDependencies: [TargetDependency] { [] }
}

public protocol InfoPlists {
	static var appInfoPlist: InfoPlist { get }
}

public extension InfoPlists {
	static var appInfoPlist: InfoPlist { .extendingDefault(with: [:]) }
}

public protocol BundlePrefixes {
	static var appBundlePrefix: String { get }
}

public extension BundlePrefixes {
	static var appBundlePrefix: String { environment.organizationName }
}

public protocol TargetSettings {
	static var appSettings: Settings? { get }
}

public extension TargetSettings {
	static var appSettings: Settings? { nil }
}

public protocol TargetScripts {
	static var appTargetScripts: [TargetScript] { get }
}

public extension TargetScripts {
	static var appTargetScripts: [TargetScript] { [] }
}

public protocol CoreDataModels {
	static var appCoreDataModels: [CoreDataModel] { get }
}

public extension CoreDataModels {
	static var appCoreDataModels: [CoreDataModel] { [] }
}
