import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
	name: environment.name,
	projects: [
		"Projects/**"
	],
	generationOptions: .options(
		autogeneratedWorkspaceSchemes: .disabled
	)
)
